name: worldwide_salah
description: A comprehensive Islamic prayer times app for Muslims worldwide
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Location Services
  geolocator: ^10.0.0
  geocoding: ^2.1.0
  
  # Data Storage
  shared_preferences: ^2.2.0
  
  # Notifications
  flutter_local_notifications: ^17.1.0
  
  # Date and Time Formatting
  intl: ^0.18.0
  
  # Prayer Time Calculations
  adhan: ^2.0.0
  
  # Qiblah Direction - USE PUB.DEV VERSION, NOT GIT
  flutter_compass: ^0.8.0
  
  # UI Components
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true